from django.urls import path

from .views import (
    BookCreateView,
    BookDeleteView,
    BookDetailView,
    BookListView,
    BookUpdateView,
    CompletionReviewUpdateView,
    DashboardView,
    ReadingNoteCreateView,
    ReadingNoteDeleteView,
    ReadingNoteUpdateView,
    BookImportView,
    BookSearchView,
    CatalogBookAddToShelfView,
    CatalogBookCategoryAddView,
    CatalogBookDetailView,
    CatalogBookListView,
    CategoryDeleteView,
    CategoryUpdateView,
    ForumCreateView,
    ForumDetailView,
    ForumPostCreateView,
    ForumPostDeleteView,
    ForumPostUpdateView,
)


urlpatterns = [
    path("", BookListView.as_view(), name="book-list"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("explore/", CatalogBookListView.as_view(), name="catalog-book-list"),
    path("explore/<int:pk>/", CatalogBookDetailView.as_view(), name="catalog-book-detail"),
    path("explore/<int:pk>/add/", CatalogBookAddToShelfView.as_view(), name="catalog-book-add"),
    path("explore/<int:pk>/categories/", CatalogBookCategoryAddView.as_view(), name="catalog-category-add"),
    path("search-books/", BookSearchView.as_view(), name="book-search"),
    path("import-book/", BookImportView.as_view(), name="book-import"),
    path("books/add/", BookCreateView.as_view(), name="book-add"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/edit/", BookUpdateView.as_view(), name="book-edit"),
    path("books/<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path(
        "books/<int:pk>/review/",
        CompletionReviewUpdateView.as_view(),
        name="book-review",
    ),
    path(
        "books/<int:book_pk>/notes/add/",
        ReadingNoteCreateView.as_view(),
        name="note-add",
    ),
    path(
        "notes/<int:pk>/edit/",
        ReadingNoteUpdateView.as_view(),
        name="note-edit",
    ),
    path(
        "notes/<int:pk>/delete/",
        ReadingNoteDeleteView.as_view(),
        name="note-delete",
    ),
    path("books/<int:book_pk>/forum/create/", ForumCreateView.as_view(), name="forum-create"),
    path("forums/<int:pk>/", ForumDetailView.as_view(), name="forum-detail"),
    path("forums/<int:forum_pk>/posts/add/", ForumPostCreateView.as_view(), name="forum-post-add"),
    path("forum-posts/<int:pk>/edit/", ForumPostUpdateView.as_view(), name="forum-post-edit"),
    path("forum-posts/<int:pk>/delete/", ForumPostDeleteView.as_view(), name="forum-post-delete"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category-edit"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),
]
