from django.urls import path

from .views import (
    BookCreateView,
    BookDeleteView,
    BookDetailView,
    BookListView,
    BookUpdateView,
    BookStatusUpdateView,
    DashboardView,
    ReadingNoteCreateView,
    ReadingNoteDeleteView,
    ReadingNoteUpdateView,
    BookImportView,
    BookSearchView,
    CatalogBookAddToShelfView,
    CatalogBookCategoryAddView,
    CatalogBookDetailView,
    CatalogBookListView,
    CategoryDeleteView,
    CategoryUpdateView,
    ForumCreateView,
    ForumDeleteView,
    ForumDetailView,
    ForumPostCreateView,
    ForumPostDeleteView,
    ForumPostUpdateView,
    ForumReplyCreateView,
    ForumReplyDeleteView,
    ForumReplyUpdateView,
    ForumUpdateView,
    ModerationDashboardView,
    PublicReviewDeleteView,
    PublicReviewUpdateView,
    PublicReviewUpsertView,
    ReadingListBookAddView,
    ReadingListBookRemoveView,
    ReadingListCreateView,
    ReadingListDeleteView,
    ReadingListDetailView,
    ReadingListListView,
    ReadingListUpdateView,
)


urlpatterns = [
    path("", BookListView.as_view(), name="book-list"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("explore/", CatalogBookListView.as_view(), name="catalog-book-list"),
    path("explore/<int:pk>/", CatalogBookDetailView.as_view(), name="catalog-book-detail"),
    path("explore/<int:pk>/add/", CatalogBookAddToShelfView.as_view(), name="catalog-book-add"),
    path("explore/<int:pk>/categories/", CatalogBookCategoryAddView.as_view(), name="catalog-category-add"),
    path("search-books/", BookSearchView.as_view(), name="book-search"),
    path("import-book/", BookImportView.as_view(), name="book-import"),
    path("books/add/", BookCreateView.as_view(), name="book-add"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book-detail"),
    path("books/<int:pk>/edit/", BookUpdateView.as_view(), name="book-edit"),
    path("books/<int:pk>/delete/", BookDeleteView.as_view(), name="book-delete"),
    path("books/<int:pk>/status/", BookStatusUpdateView.as_view(), name="book-status"),
    path("explore/<int:book_pk>/review/", PublicReviewUpsertView.as_view(), name="public-review-upsert"),
    path("reviews/<int:pk>/edit/", PublicReviewUpdateView.as_view(), name="public-review-edit"),
    path("reviews/<int:pk>/delete/", PublicReviewDeleteView.as_view(), name="public-review-delete"),
    path("lists/", ReadingListListView.as_view(), name="reading-list-list"),
    path("lists/create/", ReadingListCreateView.as_view(), name="reading-list-create"),
    path("lists/<int:pk>/", ReadingListDetailView.as_view(), name="reading-list-detail"),
    path("lists/<int:pk>/edit/", ReadingListUpdateView.as_view(), name="reading-list-edit"),
    path("lists/<int:pk>/delete/", ReadingListDeleteView.as_view(), name="reading-list-delete"),
    path("lists/<int:list_pk>/books/<int:book_pk>/add/", ReadingListBookAddView.as_view(), name="reading-list-book-add"),
    path("lists/<int:list_pk>/books/<int:book_pk>/remove/", ReadingListBookRemoveView.as_view(), name="reading-list-book-remove"),
    path(
        "books/<int:book_pk>/notes/add/",
        ReadingNoteCreateView.as_view(),
        name="note-add",
    ),
    path(
        "notes/<int:pk>/edit/",
        ReadingNoteUpdateView.as_view(),
        name="note-edit",
    ),
    path(
        "notes/<int:pk>/delete/",
        ReadingNoteDeleteView.as_view(),
        name="note-delete",
    ),
    path("books/<int:book_pk>/forum/create/", ForumCreateView.as_view(), name="forum-create"),
    path("forums/<int:pk>/", ForumDetailView.as_view(), name="forum-detail"),
    path("forums/<int:pk>/edit/", ForumUpdateView.as_view(), name="forum-edit"),
    path("forums/<int:pk>/delete/", ForumDeleteView.as_view(), name="forum-delete"),
    path("forums/<int:forum_pk>/posts/add/", ForumPostCreateView.as_view(), name="forum-post-add"),
    path("forum-posts/<int:pk>/edit/", ForumPostUpdateView.as_view(), name="forum-post-edit"),
    path("forum-posts/<int:pk>/delete/", ForumPostDeleteView.as_view(), name="forum-post-delete"),
    path("forum-posts/<int:post_pk>/replies/add/", ForumReplyCreateView.as_view(), name="forum-reply-add"),
    path("forum-replies/<int:pk>/edit/", ForumReplyUpdateView.as_view(), name="forum-reply-edit"),
    path("forum-replies/<int:pk>/delete/", ForumReplyDeleteView.as_view(), name="forum-reply-delete"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category-edit"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),
    path("moderation/", ModerationDashboardView.as_view(), name="moderation-dashboard"),
]
