# Generated by Django 5.2.16 on 2026-08-04 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_catalog_records_for_existing_books(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    CatalogBook = apps.get_model("books", "CatalogBook")
    for book in Book.objects.filter(catalog_book__isnull=True).iterator():
        catalog_book = CatalogBook.objects.create(
            title=book.title,
            author=book.author,
            added_by_id=book.owner_id,
        )
        book.catalog_book_id = catalog_book.pk
        book.save(update_fields=["catalog_book"])


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_completion_date_book_rating_book_reflection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('source', models.CharField(choices=[('api', 'Book API'), ('user', 'User created')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn_10', models.CharField(blank=True, db_index=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, db_index=True, max_length=13)),
                ('open_library_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('cover_url', models.URLField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_books_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'author'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='catalog_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelf_entries', to='books.catalogbook'),
        ),
        migrations.RunPython(
            create_catalog_records_for_existing_books,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_book__isnull', False)), fields=('owner', 'catalog_book'), name='unique_catalog_book_per_owner'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogbook',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.category'),
        ),
        migrations.AddField(
            model_name='forum',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='books.catalogbook'),
        ),
        migrations.AddField(
            model_name='forum',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='books.forum'),
        ),
    ]
